import type { EmojiData, EmojiCategory } from "./types";

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { id: "all", name: "All", icon: "🔍", order: 0 },
  { id: "smileys", name: "Smileys & Emotion", icon: "😀", order: 1 },
  { id: "people", name: "People & Body", icon: "👥", order: 2 },
  { id: "animals", name: "Animals & Nature", icon: "🐾", order: 3 },
  { id: "food", name: "Food & Drink", icon: "🍎", order: 4 },
  { id: "activities", name: "Activities", icon: "⚽", order: 5 },
  { id: "travel", name: "Travel & Places", icon: "🌍", order: 6 },
  { id: "objects", name: "Objects", icon: "💡", order: 7 },
  { id: "symbols", name: "Symbols", icon: "🎭", order: 8 },
  { id: "flags", name: "Flags", icon: "🏁", order: 9 },
];

export const EMOJI_DATA: EmojiData[] = [
  // Smileys & Emotion
  {
    emoji: "😀",
    name: "Grinning Face",
    unicode: "U+1F600",
    category: EMOJI_CATEGORIES[1],
    aliases: ["grinning", "smile"],
    keywords: ["happy", "joy", "cheerful", "face"],
    skinToneSupport: false,
  },
  {
    emoji: "😃",
    name: "Grinning Face with Big Eyes",
    unicode: "U+1F603",
    category: EMOJI_CATEGORIES[1],
    aliases: ["smiley"],
    keywords: ["happy", "joy", "cheerful", "face", "excited"],
    skinToneSupport: false,
  },
  {
    emoji: "😄",
    name: "Grinning Face with Smiling Eyes",
    unicode: "U+1F604",
    category: EMOJI_CATEGORIES[1],
    aliases: ["smile"],
    keywords: ["happy", "joy", "cheerful", "face", "laugh"],
    skinToneSupport: false,
  },
  {
    emoji: "😁",
    name: "Beaming Face with Smiling Eyes",
    unicode: "U+1F601",
    category: EMOJI_CATEGORIES[1],
    aliases: ["grin"],
    keywords: ["happy", "joy", "cheerful", "face", "beam"],
    skinToneSupport: false,
  },
  {
    emoji: "😆",
    name: "Grinning Squinting Face",
    unicode: "U+1F606",
    category: EMOJI_CATEGORIES[1],
    aliases: ["laughing", "satisfied"],
    keywords: ["happy", "joy", "laugh", "face", "squint"],
    skinToneSupport: false,
  },
  {
    emoji: "😅",
    name: "Grinning Face with Sweat",
    unicode: "U+1F605",
    category: EMOJI_CATEGORIES[1],
    aliases: ["sweat_smile"],
    keywords: ["happy", "relief", "sweat", "face", "exercise"],
    skinToneSupport: false,
  },
  {
    emoji: "🤣",
    name: "Rolling on the Floor Laughing",
    unicode: "U+1F923",
    category: EMOJI_CATEGORIES[1],
    aliases: ["rofl"],
    keywords: ["laugh", "funny", "hilarious", "face", "rolling"],
    skinToneSupport: false,
  },
  {
    emoji: "😂",
    name: "Face with Tears of Joy",
    unicode: "U+1F602",
    category: EMOJI_CATEGORIES[1],
    aliases: ["joy"],
    keywords: ["laugh", "tears", "funny", "face", "cry"],
    skinToneSupport: false,
  },
  {
    emoji: "🙂",
    name: "Slightly Smiling Face",
    unicode: "U+1F642",
    category: EMOJI_CATEGORIES[1],
    aliases: ["slightly_smiling_face"],
    keywords: ["smile", "happy", "face", "gentle"],
    skinToneSupport: false,
  },
  {
    emoji: "🙃",
    name: "Upside-Down Face",
    unicode: "U+1F643",
    category: EMOJI_CATEGORIES[1],
    aliases: ["upside_down_face"],
    keywords: ["silly", "flip", "face", "ironic"],
    skinToneSupport: false,
  },
  {
    emoji: "😉",
    name: "Winking Face",
    unicode: "U+1F609",
    category: EMOJI_CATEGORIES[1],
    aliases: ["wink"],
    keywords: ["flirt", "face", "wink", "playful"],
    skinToneSupport: false,
  },
  {
    emoji: "😊",
    name: "Smiling Face with Smiling Eyes",
    unicode: "U+1F60A",
    category: EMOJI_CATEGORIES[1],
    aliases: ["blush"],
    keywords: ["happy", "blush", "smile", "face", "sweet"],
    skinToneSupport: false,
  },
  {
    emoji: "😇",
    name: "Smiling Face with Halo",
    unicode: "U+1F607",
    category: EMOJI_CATEGORIES[1],
    aliases: ["innocent"],
    keywords: ["angel", "innocent", "face", "halo", "good"],
    skinToneSupport: false,
  },
  {
    emoji: "❤️",
    name: "Red Heart",
    unicode: "U+2764",
    category: EMOJI_CATEGORIES[1],
    aliases: ["heart"],
    keywords: ["love", "heart", "red", "emotion"],
    skinToneSupport: false,
  },
  {
    emoji: "😍",
    name: "Smiling Face with Heart-Eyes",
    unicode: "U+1F60D",
    category: EMOJI_CATEGORIES[1],
    aliases: ["heart_eyes"],
    keywords: ["love", "heart", "face", "adore", "crush"],
    skinToneSupport: false,
  },
  {
    emoji: "😘",
    name: "Face Blowing a Kiss",
    unicode: "U+1F618",
    category: EMOJI_CATEGORIES[1],
    aliases: ["kissing_heart"],
    keywords: ["kiss", "love", "face", "blow", "heart"],
    skinToneSupport: false,
  },
  {
    emoji: "😭",
    name: "Loudly Crying Face",
    unicode: "U+1F62D",
    category: EMOJI_CATEGORIES[1],
    aliases: ["sob"],
    keywords: ["cry", "tears", "sad", "face", "weep"],
    skinToneSupport: false,
  },
  {
    emoji: "😢",
    name: "Crying Face",
    unicode: "U+1F622",
    category: EMOJI_CATEGORIES[1],
    aliases: ["cry"],
    keywords: ["cry", "tears", "sad", "face", "upset"],
    skinToneSupport: false,
  },
  {
    emoji: "😤",
    name: "Face with Steam From Nose",
    unicode: "U+1F624",
    category: EMOJI_CATEGORIES[1],
    aliases: ["triumph"],
    keywords: ["angry", "mad", "face", "steam", "nose"],
    skinToneSupport: false,
  },
  {
    emoji: "😠",
    name: "Angry Face",
    unicode: "U+1F620",
    category: EMOJI_CATEGORIES[1],
    aliases: ["angry"],
    keywords: ["angry", "mad", "face", "upset", "furious"],
    skinToneSupport: false,
  },

  // People & Body
  {
    emoji: "👍",
    name: "Thumbs Up",
    unicode: "U+1F44D",
    category: EMOJI_CATEGORIES[2],
    aliases: ["+1", "thumbsup"],
    keywords: ["good", "yes", "approve", "hand", "like"],
    skinToneSupport: true,
    variations: ["👍🏻", "👍🏼", "👍🏽", "👍🏾", "👍🏿"],
  },
  {
    emoji: "👎",
    name: "Thumbs Down",
    unicode: "U+1F44E",
    category: EMOJI_CATEGORIES[2],
    aliases: ["-1", "thumbsdown"],
    keywords: ["bad", "no", "disapprove", "hand", "dislike"],
    skinToneSupport: true,
    variations: ["👎🏻", "👎🏼", "👎🏽", "👎🏾", "👎🏿"],
  },
  {
    emoji: "👏",
    name: "Clapping Hands",
    unicode: "U+1F44F",
    category: EMOJI_CATEGORIES[2],
    aliases: ["clap"],
    keywords: ["applause", "clap", "hands", "praise", "congratulations"],
    skinToneSupport: true,
    variations: ["👏🏻", "👏🏼", "👏🏽", "👏🏾", "👏🏿"],
  },
  {
    emoji: "🙌",
    name: "Raising Hands",
    unicode: "U+1F64C",
    category: EMOJI_CATEGORIES[2],
    aliases: ["raised_hands"],
    keywords: ["celebration", "praise", "hands", "hooray", "success"],
    skinToneSupport: true,
    variations: ["🙌🏻", "🙌🏼", "🙌🏽", "🙌🏾", "🙌🏿"],
  },
  {
    emoji: "🤝",
    name: "Handshake",
    unicode: "U+1F91D",
    category: EMOJI_CATEGORIES[2],
    aliases: ["handshake"],
    keywords: ["deal", "agreement", "hands", "cooperation", "partnership"],
    skinToneSupport: false,
  },
  {
    emoji: "🙏",
    name: "Folded Hands",
    unicode: "U+1F64F",
    category: EMOJI_CATEGORIES[2],
    aliases: ["pray"],
    keywords: ["pray", "thanks", "hands", "grateful", "please"],
    skinToneSupport: true,
    variations: ["🙏🏻", "🙏🏼", "🙏🏽", "🙏🏾", "🙏🏿"],
  },

  // Animals & Nature
  {
    emoji: "🐶",
    name: "Dog Face",
    unicode: "U+1F436",
    category: EMOJI_CATEGORIES[3],
    aliases: ["dog"],
    keywords: ["dog", "pet", "animal", "puppy", "cute"],
    skinToneSupport: false,
  },
  {
    emoji: "🐱",
    name: "Cat Face",
    unicode: "U+1F431",
    category: EMOJI_CATEGORIES[3],
    aliases: ["cat"],
    keywords: ["cat", "pet", "animal", "kitten", "cute"],
    skinToneSupport: false,
  },
  {
    emoji: "🦊",
    name: "Fox",
    unicode: "U+1F98A",
    category: EMOJI_CATEGORIES[3],
    aliases: ["fox"],
    keywords: ["fox", "animal", "wild", "cute", "clever"],
    skinToneSupport: false,
  },
  {
    emoji: "🐻",
    name: "Bear",
    unicode: "U+1F43B",
    category: EMOJI_CATEGORIES[3],
    aliases: ["bear"],
    keywords: ["bear", "animal", "wild", "strong", "nature"],
    skinToneSupport: false,
  },
  {
    emoji: "🐼",
    name: "Panda",
    unicode: "U+1F43C",
    category: EMOJI_CATEGORIES[3],
    aliases: ["panda_face"],
    keywords: ["panda", "animal", "cute", "china", "black", "white"],
    skinToneSupport: false,
  },
  {
    emoji: "🦁",
    name: "Lion",
    unicode: "U+1F981",
    category: EMOJI_CATEGORIES[3],
    aliases: ["lion"],
    keywords: ["lion", "animal", "king", "strong", "wild"],
    skinToneSupport: false,
  },
  {
    emoji: "🐸",
    name: "Frog",
    unicode: "U+1F438",
    category: EMOJI_CATEGORIES[3],
    aliases: ["frog"],
    keywords: ["frog", "animal", "green", "pond", "amphibian"],
    skinToneSupport: false,
  },
  {
    emoji: "🦄",
    name: "Unicorn",
    unicode: "U+1F984",
    category: EMOJI_CATEGORIES[3],
    aliases: ["unicorn"],
    keywords: ["unicorn", "fantasy", "magical", "rainbow", "horn"],
    skinToneSupport: false,
  },
  {
    emoji: "🌟",
    name: "Glowing Star",
    unicode: "U+1F31F",
    category: EMOJI_CATEGORIES[3],
    aliases: ["star2"],
    keywords: ["star", "bright", "shine", "sparkle", "glow"],
    skinToneSupport: false,
  },
  {
    emoji: "⭐",
    name: "Star",
    unicode: "U+2B50",
    category: EMOJI_CATEGORIES[3],
    aliases: ["star"],
    keywords: ["star", "favorite", "rating", "night", "sky"],
    skinToneSupport: false,
  },

  // Food & Drink
  {
    emoji: "🍎",
    name: "Red Apple",
    unicode: "U+1F34E",
    category: EMOJI_CATEGORIES[4],
    aliases: ["apple"],
    keywords: ["apple", "fruit", "healthy", "red", "teacher"],
    skinToneSupport: false,
  },
  {
    emoji: "🍕",
    name: "Pizza",
    unicode: "U+1F355",
    category: EMOJI_CATEGORIES[4],
    aliases: ["pizza"],
    keywords: ["pizza", "food", "italian", "cheese", "slice"],
    skinToneSupport: false,
  },
  {
    emoji: "🍔",
    name: "Hamburger",
    unicode: "U+1F354",
    category: EMOJI_CATEGORIES[4],
    aliases: ["hamburger"],
    keywords: ["burger", "food", "meat", "fast", "meal"],
    skinToneSupport: false,
  },
  {
    emoji: "🍟",
    name: "French Fries",
    unicode: "U+1F35F",
    category: EMOJI_CATEGORIES[4],
    aliases: ["fries"],
    keywords: ["fries", "food", "potato", "fast", "golden"],
    skinToneSupport: false,
  },
  {
    emoji: "🍰",
    name: "Shortcake",
    unicode: "U+1F370",
    category: EMOJI_CATEGORIES[4],
    aliases: ["cake"],
    keywords: ["cake", "dessert", "sweet", "birthday", "celebration"],
    skinToneSupport: false,
  },
  {
    emoji: "🎂",
    name: "Birthday Cake",
    unicode: "U+1F382",
    category: EMOJI_CATEGORIES[4],
    aliases: ["birthday"],
    keywords: ["birthday", "cake", "candles", "celebration", "party"],
    skinToneSupport: false,
  },
  {
    emoji: "🍫",
    name: "Chocolate Bar",
    unicode: "U+1F36B",
    category: EMOJI_CATEGORIES[4],
    aliases: ["chocolate_bar"],
    keywords: ["chocolate", "sweet", "candy", "dessert", "treat"],
    skinToneSupport: false,
  },
  {
    emoji: "☕",
    name: "Hot Beverage",
    unicode: "U+2615",
    category: EMOJI_CATEGORIES[4],
    aliases: ["coffee"],
    keywords: ["coffee", "hot", "drink", "morning", "caffeine"],
    skinToneSupport: false,
  },

  // Activities
  {
    emoji: "⚽",
    name: "Soccer Ball",
    unicode: "U+26BD",
    category: EMOJI_CATEGORIES[5],
    aliases: ["soccer"],
    keywords: ["soccer", "football", "ball", "sport", "game"],
    skinToneSupport: false,
  },
  {
    emoji: "🏀",
    name: "Basketball",
    unicode: "U+1F3C0",
    category: EMOJI_CATEGORIES[5],
    aliases: ["basketball"],
    keywords: ["basketball", "ball", "sport", "game", "orange"],
    skinToneSupport: false,
  },
  {
    emoji: "🎉",
    name: "Party Popper",
    unicode: "U+1F389",
    category: EMOJI_CATEGORIES[5],
    aliases: ["tada"],
    keywords: ["party", "celebration", "confetti", "congratulations", "hooray"],
    skinToneSupport: false,
  },
  {
    emoji: "🎵",
    name: "Musical Note",
    unicode: "U+1F3B5",
    category: EMOJI_CATEGORIES[5],
    aliases: ["musical_note"],
    keywords: ["music", "note", "sound", "melody", "song"],
    skinToneSupport: false,
  },
  {
    emoji: "🎮",
    name: "Video Game",
    unicode: "U+1F3AE",
    category: EMOJI_CATEGORIES[5],
    aliases: ["video_game"],
    keywords: ["game", "controller", "gaming", "video", "play"],
    skinToneSupport: false,
  },
  {
    emoji: "🎯",
    name: "Direct Hit",
    unicode: "U+1F3AF",
    category: EMOJI_CATEGORIES[5],
    aliases: ["dart"],
    keywords: ["target", "bullseye", "dart", "accurate", "goal"],
    skinToneSupport: false,
  },

  // Travel & Places
  {
    emoji: "🌍",
    name: "Globe Showing Europe-Africa",
    unicode: "U+1F30D",
    category: EMOJI_CATEGORIES[6],
    aliases: ["earth_africa"],
    keywords: ["earth", "world", "globe", "planet", "africa", "europe"],
    skinToneSupport: false,
  },
  {
    emoji: "🌎",
    name: "Globe Showing Americas",
    unicode: "U+1F30E",
    category: EMOJI_CATEGORIES[6],
    aliases: ["earth_americas"],
    keywords: ["earth", "world", "globe", "planet", "americas"],
    skinToneSupport: false,
  },
  {
    emoji: "🏠",
    name: "House",
    unicode: "U+1F3E0",
    category: EMOJI_CATEGORIES[6],
    aliases: ["house"],
    keywords: ["house", "home", "building", "family", "residence"],
    skinToneSupport: false,
  },
  {
    emoji: "🚀",
    name: "Rocket",
    unicode: "U+1F680",
    category: EMOJI_CATEGORIES[6],
    aliases: ["rocket"],
    keywords: ["rocket", "space", "launch", "fast", "ship"],
    skinToneSupport: false,
  },
  {
    emoji: "✈️",
    name: "Airplane",
    unicode: "U+2708",
    category: EMOJI_CATEGORIES[6],
    aliases: ["airplane"],
    keywords: ["airplane", "travel", "fly", "trip", "vacation"],
    skinToneSupport: false,
  },
  {
    emoji: "🚗",
    name: "Automobile",
    unicode: "U+1F697",
    category: EMOJI_CATEGORIES[6],
    aliases: ["car"],
    keywords: ["car", "automobile", "vehicle", "drive", "road"],
    skinToneSupport: false,
  },

  // Objects
  {
    emoji: "💡",
    name: "Light Bulb",
    unicode: "U+1F4A1",
    category: EMOJI_CATEGORIES[7],
    aliases: ["bulb"],
    keywords: ["idea", "light", "bulb", "bright", "innovation"],
    skinToneSupport: false,
  },
  {
    emoji: "📱",
    name: "Mobile Phone",
    unicode: "U+1F4F1",
    category: EMOJI_CATEGORIES[7],
    aliases: ["iphone"],
    keywords: ["phone", "mobile", "cell", "smartphone", "device"],
    skinToneSupport: false,
  },
  {
    emoji: "💻",
    name: "Laptop",
    unicode: "U+1F4BB",
    category: EMOJI_CATEGORIES[7],
    aliases: ["computer"],
    keywords: ["laptop", "computer", "work", "technology", "coding"],
    skinToneSupport: false,
  },
  {
    emoji: "📝",
    name: "Memo",
    unicode: "U+1F4DD",
    category: EMOJI_CATEGORIES[7],
    aliases: ["memo", "pencil"],
    keywords: ["memo", "note", "write", "document", "text"],
    skinToneSupport: false,
  },
  {
    emoji: "🔥",
    name: "Fire",
    unicode: "U+1F525",
    category: EMOJI_CATEGORIES[7],
    aliases: ["fire"],
    keywords: ["fire", "hot", "flame", "burn", "trending"],
    skinToneSupport: false,
  },
  {
    emoji: "💎",
    name: "Gem Stone",
    unicode: "U+1F48E",
    category: EMOJI_CATEGORIES[7],
    aliases: ["gem"],
    keywords: ["gem", "diamond", "precious", "jewelry", "valuable"],
    skinToneSupport: false,
  },

  // Symbols
  {
    emoji: "✅",
    name: "Check Mark Button",
    unicode: "U+2705",
    category: EMOJI_CATEGORIES[8],
    aliases: ["white_check_mark"],
    keywords: ["check", "mark", "yes", "correct", "done"],
    skinToneSupport: false,
  },
  {
    emoji: "❌",
    name: "Cross Mark",
    unicode: "U+274C",
    category: EMOJI_CATEGORIES[8],
    aliases: ["x"],
    keywords: ["cross", "mark", "no", "wrong", "error"],
    skinToneSupport: false,
  },
  {
    emoji: "⚠️",
    name: "Warning",
    unicode: "U+26A0",
    category: EMOJI_CATEGORIES[8],
    aliases: ["warning"],
    keywords: ["warning", "caution", "alert", "danger", "attention"],
    skinToneSupport: false,
  },
  {
    emoji: "💯",
    name: "Hundred Points",
    unicode: "U+1F4AF",
    category: EMOJI_CATEGORIES[8],
    aliases: ["100"],
    keywords: ["hundred", "perfect", "score", "full", "complete"],
    skinToneSupport: false,
  },
  {
    emoji: "🔔",
    name: "Bell",
    unicode: "U+1F514",
    category: EMOJI_CATEGORIES[8],
    aliases: ["bell"],
    keywords: ["bell", "sound", "notification", "ring", "alert"],
    skinToneSupport: false,
  },
  {
    emoji: "💖",
    name: "Sparkling Heart",
    unicode: "U+1F496",
    category: EMOJI_CATEGORIES[8],
    aliases: ["sparkling_heart"],
    keywords: ["love", "heart", "sparkle", "emotion", "affection"],
    skinToneSupport: false,
  },

  // Flags
  {
    emoji: "🏁",
    name: "Chequered Flag",
    unicode: "U+1F3C1",
    category: EMOJI_CATEGORIES[9],
    aliases: ["checkered_flag"],
    keywords: ["flag", "finish", "race", "complete", "end"],
    skinToneSupport: false,
  },
  {
    emoji: "🇺🇸",
    name: "Flag: United States",
    unicode: "U+1F1FA U+1F1F8",
    category: EMOJI_CATEGORIES[9],
    aliases: ["us", "flag-us"],
    keywords: ["flag", "united", "states", "america", "usa"],
    skinToneSupport: false,
  },
  {
    emoji: "🇨🇳",
    name: "Flag: China",
    unicode: "U+1F1E8 U+1F1F3",
    category: EMOJI_CATEGORIES[9],
    aliases: ["cn", "flag-cn"],
    keywords: ["flag", "china", "chinese"],
    skinToneSupport: false,
  },
  {
    emoji: "🇯🇵",
    name: "Flag: Japan",
    unicode: "U+1F1EF U+1F1F5",
    category: EMOJI_CATEGORIES[9],
    aliases: ["jp", "flag-jp"],
    keywords: ["flag", "japan", "japanese"],
    skinToneSupport: false,
  },
  {
    emoji: "🇬🇧",
    name: "Flag: United Kingdom",
    unicode: "U+1F1EC U+1F1E7",
    category: EMOJI_CATEGORIES[9],
    aliases: ["gb", "uk", "flag-gb"],
    keywords: ["flag", "united", "kingdom", "britain", "british"],
    skinToneSupport: false,
  },
];

export const getEmojisByCategory = (categoryId: string): EmojiData[] => {
  if (categoryId === "all") {
    return EMOJI_DATA;
  }
  return EMOJI_DATA.filter((emoji) => emoji.category.id === categoryId);
};

export const searchEmojis = (query: string): EmojiData[] => {
  if (!query.trim()) {
    return EMOJI_DATA;
  }

  const searchTerm = query.toLowerCase();
  return EMOJI_DATA.filter(
    (emoji) =>
      emoji.name.toLowerCase().includes(searchTerm) ||
      emoji.aliases.some((alias) => alias.toLowerCase().includes(searchTerm)) ||
      emoji.keywords.some((keyword) =>
        keyword.toLowerCase().includes(searchTerm)
      )
  );
};
