import type { UnitCategory } from "../types";

/**
 * Unit Categories Configuration
 * Complete unit definitions organized by category and group
 */
export const unitCategories: UnitCategory[] = [
  {
    id: "length",
    name: "Length",
    icon: "L",
    description: "Linear measurements from nanometers to light-years",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "meter",
            name: "Meter",
            symbol: "m",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI base unit of length",
            context: "Standard metric measurement for everyday distances",
          },
          {
            id: "centimeter",
            name: "Centimeter",
            symbol: "cm",
            baseRatio: 0.01,
            isBaseUnit: false,
            precision: 2,
            description: "1/100 of a meter",
            context: "Ideal for measuring small objects and body measurements",
          },
          {
            id: "millimeter",
            name: "Millimeter",
            symbol: "mm",
            baseRatio: 0.001,
            isBaseUnit: false,
            precision: 2,
            description: "1/1000 of a meter",
            context: "Precision measurements and engineering",
          },
          {
            id: "kilometer",
            name: "Kilometer",
            symbol: "km",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 6,
            description: "1000 meters",
            context: "Measuring long distances and geographical scales",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "inch",
            name: "Inch",
            symbol: "in",
            baseRatio: 0.0254,
            isBaseUnit: false,
            precision: 3,
            description: "Imperial unit, 1/12 of a foot",
            context: "Common in US for construction and manufacturing",
          },
          {
            id: "foot",
            name: "Foot",
            symbol: "ft",
            baseRatio: 0.3048,
            isBaseUnit: false,
            precision: 3,
            description: "12 inches",
            context: "Height measurements and construction",
          },
          {
            id: "yard",
            name: "Yard",
            symbol: "yd",
            baseRatio: 0.9144,
            isBaseUnit: false,
            precision: 3,
            description: "3 feet",
            context: "Sports fields and fabric measurements",
          },
          {
            id: "mile",
            name: "Mile",
            symbol: "mi",
            baseRatio: 1609.344,
            isBaseUnit: false,
            precision: 6,
            description: "5280 feet",
            context: "Long distances and road measurements",
          },
        ],
      },
      {
        id: "scientific",
        name: "Scientific Units",
        units: [
          {
            id: "micrometer",
            name: "Micrometer",
            symbol: "μm",
            baseRatio: 1e-6,
            isBaseUnit: false,
            precision: 2,
            scientificNotation: true,
            description: "One millionth of a meter",
            context: "Microscopy and cell measurements",
          },
          {
            id: "nanometer",
            name: "Nanometer",
            symbol: "nm",
            baseRatio: 1e-9,
            isBaseUnit: false,
            precision: 2,
            scientificNotation: true,
            description: "One billionth of a meter",
            context: "Nanotechnology and atomic measurements",
          },
        ],
      },
    ],
  },
  {
    id: "weight",
    name: "Weight",
    icon: "W",
    description: "Mass and weight measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "gram",
            name: "Gram",
            symbol: "g",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "Base unit of mass in metric system",
            context: "Small mass measurements and cooking",
          },
          {
            id: "kilogram",
            name: "Kilogram",
            symbol: "kg",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 6,
            description: "1000 grams",
            context: "SI base unit for mass, body weight",
          },
          {
            id: "milligram",
            name: "Milligram",
            symbol: "mg",
            baseRatio: 0.001,
            isBaseUnit: false,
            precision: 3,
            description: "1/1000 of a gram",
            context: "Medicine dosage and precision measurements",
          },
          {
            id: "tonne",
            name: "Tonne",
            symbol: "t",
            baseRatio: 1000000,
            isBaseUnit: false,
            precision: 6,
            description: "1000 kilograms",
            context: "Large mass measurements, industrial use",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "ounce",
            name: "Ounce",
            symbol: "oz",
            baseRatio: 28.3495,
            isBaseUnit: false,
            precision: 3,
            description: "1/16 of a pound",
            context: "Small weight measurements, precious metals",
          },
          {
            id: "pound",
            name: "Pound",
            symbol: "lb",
            baseRatio: 453.592,
            isBaseUnit: false,
            precision: 3,
            description: "16 ounces",
            context: "Body weight and general measurements in US",
          },
          {
            id: "stone",
            name: "Stone",
            symbol: "st",
            baseRatio: 6350.29,
            isBaseUnit: false,
            precision: 3,
            description: "14 pounds",
            context: "Body weight measurements in UK",
          },
        ],
      },
    ],
  },
  {
    id: "temperature",
    name: "Temperature",
    icon: "T",
    description: "Temperature measurements in different scales",
    groups: [
      {
        id: "common",
        name: "Common Scales",
        units: [
          {
            id: "celsius",
            name: "Celsius",
            symbol: "°C",
            baseRatio: 1,
            baseOffset: 273.15,
            isBaseUnit: false,
            precision: 2,
            description: "Water freezes at 0°C, boils at 100°C",
            context: "Standard temperature scale in most countries",
          },
          {
            id: "fahrenheit",
            name: "Fahrenheit",
            symbol: "°F",
            baseRatio: 5 / 9,
            baseOffset: 459.67,
            isBaseUnit: false,
            precision: 2,
            description: "Water freezes at 32°F, boils at 212°F",
            context: "Primary temperature scale in the United States",
          },
          {
            id: "kelvin",
            name: "Kelvin",
            symbol: "K",
            baseRatio: 1,
            baseOffset: 0,
            isBaseUnit: true,
            precision: 2,
            description: "Absolute temperature scale starting at absolute zero",
            context: "SI base unit, used in scientific calculations",
          },
        ],
      },
    ],
  },
  {
    id: "volume",
    name: "Volume",
    icon: "V",
    description: "Liquid and volume measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "liter",
            name: "Liter",
            symbol: "L",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "Base unit for liquid volume",
            context: "Standard liquid measurements",
          },
          {
            id: "milliliter",
            name: "Milliliter",
            symbol: "mL",
            baseRatio: 0.001,
            isBaseUnit: false,
            precision: 2,
            description: "1/1000 of a liter",
            context: "Small liquid amounts, medicine",
          },
          {
            id: "cubic_meter",
            name: "Cubic Meter",
            symbol: "m³",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 6,
            description: "1000 liters",
            context: "Large volume measurements, construction",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "fluid_ounce",
            name: "Fluid Ounce",
            symbol: "fl oz",
            baseRatio: 0.0295735,
            isBaseUnit: false,
            precision: 3,
            description: "US fluid ounce",
            context: "Small liquid measurements in recipes",
          },
          {
            id: "cup",
            name: "Cup",
            symbol: "cup",
            baseRatio: 0.236588,
            isBaseUnit: false,
            precision: 3,
            description: "8 fluid ounces",
            context: "Cooking and baking measurements",
          },
          {
            id: "gallon",
            name: "Gallon",
            symbol: "gal",
            baseRatio: 3.78541,
            isBaseUnit: false,
            precision: 3,
            description: "US gallon, 128 fluid ounces",
            context: "Large liquid volumes, fuel measurements",
          },
        ],
      },
    ],
  },
  {
    id: "area",
    name: "Area",
    icon: "A",
    description: "Surface area measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "square_meter",
            name: "Square Meter",
            symbol: "m²",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI unit of area",
            context: "Room sizes, land measurements",
          },
          {
            id: "square_centimeter",
            name: "Square Centimeter",
            symbol: "cm²",
            baseRatio: 0.0001,
            isBaseUnit: false,
            precision: 2,
            description: "Small area measurements",
            context: "Small surfaces, cross-sections",
          },
          {
            id: "hectare",
            name: "Hectare",
            symbol: "ha",
            baseRatio: 10000,
            isBaseUnit: false,
            precision: 6,
            description: "10,000 square meters",
            context: "Agricultural land, large areas",
          },
        ],
      },
    ],
  },
  {
    id: "speed",
    name: "Speed",
    icon: "S",
    description: "Velocity and speed measurements",
    groups: [
      {
        id: "common",
        name: "Common Units",
        units: [
          {
            id: "meters_per_second",
            name: "Meters per Second",
            symbol: "m/s",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 3,
            description: "SI unit of speed",
            context: "Scientific calculations, physics",
          },
          {
            id: "kilometers_per_hour",
            name: "Kilometers per Hour",
            symbol: "km/h",
            baseRatio: 0.277778,
            isBaseUnit: false,
            precision: 3,
            description: "Common speed unit",
            context: "Vehicle speeds, everyday use",
          },
          {
            id: "miles_per_hour",
            name: "Miles per Hour",
            symbol: "mph",
            baseRatio: 0.44704,
            isBaseUnit: false,
            precision: 3,
            description: "Imperial speed unit",
            context: "Vehicle speeds in US and UK",
          },
          {
            id: "knots",
            name: "Knots",
            symbol: "kt",
            baseRatio: 0.514444,
            isBaseUnit: false,
            precision: 3,
            description: "Nautical miles per hour",
            context: "Maritime and aviation speeds",
          },
        ],
      },
    ],
  },
];
