import type { UnitCategory } from "../types";

/**
 * Unit Categories Configuration
 * Complete unit definitions organized by category and group
 */
export const unitCategories: UnitCategory[] = [
  {
    id: "length",
    name: "Length",
    icon: "L",
    description: "Linear measurements from nanometers to light-years",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "meter",
            name: "Meter",
            symbol: "m",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI base unit of length",
            context: "Standard metric measurement for everyday distances",
          },
          {
            id: "centimeter",
            name: "Centimeter",
            symbol: "cm",
            baseRatio: 0.01,
            isBaseUnit: false,
            precision: 2,
            description: "1/100 of a meter",
            context: "Ideal for measuring small objects and body measurements",
          },
          {
            id: "millimeter",
            name: "Millimeter",
            symbol: "mm",
            baseRatio: 0.001,
            isBaseUnit: false,
            precision: 2,
            description: "1/1000 of a meter",
            context: "Precision measurements and engineering",
          },
          {
            id: "kilometer",
            name: "Kilometer",
            symbol: "km",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 6,
            description: "1000 meters",
            context: "Measuring long distances and geographical scales",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "inch",
            name: "Inch",
            symbol: "in",
            baseRatio: 0.0254,
            isBaseUnit: false,
            precision: 3,
            description: "Imperial unit, 1/12 of a foot",
            context: "Common in US for construction and manufacturing",
          },
          {
            id: "foot",
            name: "Foot",
            symbol: "ft",
            baseRatio: 0.3048,
            isBaseUnit: false,
            precision: 3,
            description: "12 inches",
            context: "Height measurements and construction",
          },
          {
            id: "yard",
            name: "Yard",
            symbol: "yd",
            baseRatio: 0.9144,
            isBaseUnit: false,
            precision: 3,
            description: "3 feet",
            context: "Sports fields and fabric measurements",
          },
          {
            id: "mile",
            name: "Mile",
            symbol: "mi",
            baseRatio: 1609.344,
            isBaseUnit: false,
            precision: 6,
            description: "5280 feet",
            context: "Long distances and road measurements",
          },
        ],
      },
      {
        id: "scientific",
        name: "Scientific Units",
        units: [
          {
            id: "micrometer",
            name: "Micrometer",
            symbol: "μm",
            baseRatio: 1e-6,
            isBaseUnit: false,
            precision: 2,
            scientificNotation: true,
            description: "One millionth of a meter",
            context: "Microscopy and cell measurements",
          },
          {
            id: "nanometer",
            name: "Nanometer",
            symbol: "nm",
            baseRatio: 1e-9,
            isBaseUnit: false,
            precision: 2,
            scientificNotation: true,
            description: "One billionth of a meter",
            context: "Nanotechnology and atomic measurements",
          },
        ],
      },
    ],
  },
  {
    id: "weight",
    name: "Weight",
    icon: "W",
    description: "Mass and weight measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "gram",
            name: "Gram",
            symbol: "g",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "Base unit of mass in metric system",
            context: "Small mass measurements and cooking",
          },
          {
            id: "kilogram",
            name: "Kilogram",
            symbol: "kg",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 6,
            description: "1000 grams",
            context: "SI base unit for mass, body weight",
          },
          {
            id: "milligram",
            name: "Milligram",
            symbol: "mg",
            baseRatio: 0.001,
            isBaseUnit: false,
            precision: 3,
            description: "1/1000 of a gram",
            context: "Medicine dosage and precision measurements",
          },
          {
            id: "tonne",
            name: "Tonne",
            symbol: "t",
            baseRatio: 1000000,
            isBaseUnit: false,
            precision: 6,
            description: "1000 kilograms",
            context: "Large mass measurements, industrial use",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "ounce",
            name: "Ounce",
            symbol: "oz",
            baseRatio: 28.3495,
            isBaseUnit: false,
            precision: 3,
            description: "1/16 of a pound",
            context: "Small weight measurements, precious metals",
          },
          {
            id: "pound",
            name: "Pound",
            symbol: "lb",
            baseRatio: 453.592,
            isBaseUnit: false,
            precision: 3,
            description: "16 ounces",
            context: "Body weight and everyday measurements",
          },
          {
            id: "stone",
            name: "Stone",
            symbol: "st",
            baseRatio: 6350.29,
            isBaseUnit: false,
            precision: 3,
            description: "14 pounds",
            context: "Body weight in UK",
          },
          {
            id: "ton_us",
            name: "US Ton",
            symbol: "ton",
            baseRatio: 907184.74,
            isBaseUnit: false,
            precision: 6,
            description: "2000 pounds",
            context: "Heavy industrial measurements",
          },
        ],
      },
    ],
  },
  {
    id: "temperature",
    name: "Temperature",
    icon: "T",
    description: "Temperature measurements with different scales",
    groups: [
      {
        id: "common",
        name: "Common Units",
        units: [
          {
            id: "celsius",
            name: "Celsius",
            symbol: "°C",
            baseRatio: 1,
            baseOffset: 273.15,
            isBaseUnit: false,
            precision: 2,
            description: "Temperature scale based on water freezing/boiling",
            context: "Daily weather and cooking temperatures",
          },
          {
            id: "fahrenheit",
            name: "Fahrenheit",
            symbol: "°F",
            baseRatio: 5 / 9,
            baseOffset: 459.67,
            isBaseUnit: false,
            precision: 2,
            description: "Temperature scale common in US",
            context: "Weather and household temperatures in US",
          },
          {
            id: "kelvin",
            name: "Kelvin",
            symbol: "K",
            baseRatio: 1,
            baseOffset: 0,
            isBaseUnit: true,
            precision: 2,
            description: "SI base unit of temperature",
            context: "Scientific and physics calculations",
          },
        ],
      },
      {
        id: "scientific",
        name: "Scientific Units",
        units: [
          {
            id: "rankine",
            name: "Rankine",
            symbol: "°R",
            baseRatio: 5 / 9,
            baseOffset: 0,
            isBaseUnit: false,
            precision: 2,
            description: "Absolute temperature scale based on Fahrenheit",
            context: "Engineering and thermodynamics",
          },
        ],
      },
    ],
  },
  {
    id: "volume",
    name: "Volume",
    icon: "V",
    description: "Volume and capacity measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "liter",
            name: "Liter",
            symbol: "L",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "Base unit for liquid volume",
            context: "Beverages and liquid measurements",
          },
          {
            id: "milliliter",
            name: "Milliliter",
            symbol: "mL",
            baseRatio: 0.001,
            isBaseUnit: false,
            precision: 2,
            description: "1/1000 of a liter",
            context: "Medicine and small liquid measurements",
          },
          {
            id: "cubic_meter",
            name: "Cubic Meter",
            symbol: "m³",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 6,
            description: "1000 liters",
            context: "Large volume measurements",
          },
          {
            id: "cubic_centimeter",
            name: "Cubic Centimeter",
            symbol: "cm³",
            baseRatio: 0.001,
            isBaseUnit: false,
            precision: 2,
            description: "Same as milliliter",
            context: "Small volume measurements",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "gallon_us",
            name: "US Gallon",
            symbol: "gal",
            baseRatio: 3.78541,
            isBaseUnit: false,
            precision: 3,
            description: "US liquid gallon",
            context: "Fuel and large liquid measurements in US",
          },
          {
            id: "quart_us",
            name: "US Quart",
            symbol: "qt",
            baseRatio: 0.946353,
            isBaseUnit: false,
            precision: 3,
            description: "1/4 of a US gallon",
            context: "Cooking and medium liquid measurements",
          },
          {
            id: "pint_us",
            name: "US Pint",
            symbol: "pt",
            baseRatio: 0.473176,
            isBaseUnit: false,
            precision: 3,
            description: "1/2 of a US quart",
            context: "Beverages and cooking",
          },
          {
            id: "cup_us",
            name: "US Cup",
            symbol: "cup",
            baseRatio: 0.236588,
            isBaseUnit: false,
            precision: 3,
            description: "1/2 of a US pint",
            context: "Cooking and baking measurements",
          },
          {
            id: "fluid_ounce_us",
            name: "US Fluid Ounce",
            symbol: "fl oz",
            baseRatio: 0.0295735,
            isBaseUnit: false,
            precision: 3,
            description: "1/8 of a US cup",
            context: "Small liquid measurements",
          },
        ],
      },
    ],
  },
  {
    id: "area",
    name: "Area",
    icon: "A",
    description: "Surface area measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "square_meter",
            name: "Square Meter",
            symbol: "m²",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI unit of area",
            context: "Room sizes and land measurements",
          },
          {
            id: "square_centimeter",
            name: "Square Centimeter",
            symbol: "cm²",
            baseRatio: 0.0001,
            isBaseUnit: false,
            precision: 2,
            description: "1/10000 of a square meter",
            context: "Small area measurements",
          },
          {
            id: "square_kilometer",
            name: "Square Kilometer",
            symbol: "km²",
            baseRatio: 1000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000 square meters",
            context: "City and country area measurements",
          },
          {
            id: "hectare",
            name: "Hectare",
            symbol: "ha",
            baseRatio: 10000,
            isBaseUnit: false,
            precision: 6,
            description: "10,000 square meters",
            context: "Agricultural and land measurements",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "square_inch",
            name: "Square Inch",
            symbol: "in²",
            baseRatio: 0.00064516,
            isBaseUnit: false,
            precision: 3,
            description: "Area of 1 inch × 1 inch",
            context: "Small area measurements",
          },
          {
            id: "square_foot",
            name: "Square Foot",
            symbol: "ft²",
            baseRatio: 0.092903,
            isBaseUnit: false,
            precision: 3,
            description: "Area of 1 foot × 1 foot",
            context: "Room and building measurements",
          },
          {
            id: "square_yard",
            name: "Square Yard",
            symbol: "yd²",
            baseRatio: 0.836127,
            isBaseUnit: false,
            precision: 3,
            description: "Area of 1 yard × 1 yard",
            context: "Carpet and fabric measurements",
          },
          {
            id: "acre",
            name: "Acre",
            symbol: "ac",
            baseRatio: 4046.86,
            isBaseUnit: false,
            precision: 6,
            description: "43,560 square feet",
            context: "Land and property measurements",
          },
          {
            id: "square_mile",
            name: "Square Mile",
            symbol: "mi²",
            baseRatio: 2589988.11,
            isBaseUnit: false,
            precision: 6,
            description: "Area of 1 mile × 1 mile",
            context: "Large area measurements",
          },
        ],
      },
    ],
  },
  {
    id: "speed",
    name: "Speed",
    icon: "S",
    description: "Velocity and speed measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "meter_per_second",
            name: "Meter per Second",
            symbol: "m/s",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI unit of speed",
            context: "Physics and scientific calculations",
          },
          {
            id: "kilometer_per_hour",
            name: "Kilometer per Hour",
            symbol: "km/h",
            baseRatio: 0.277778,
            isBaseUnit: false,
            precision: 3,
            description: "Common speed unit",
            context: "Vehicle speeds and travel",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "mile_per_hour",
            name: "Mile per Hour",
            symbol: "mph",
            baseRatio: 0.44704,
            isBaseUnit: false,
            precision: 3,
            description: "Common speed unit in US",
            context: "Vehicle speeds in US",
          },
          {
            id: "foot_per_second",
            name: "Foot per Second",
            symbol: "ft/s",
            baseRatio: 0.3048,
            isBaseUnit: false,
            precision: 3,
            description: "Imperial speed unit",
            context: "Engineering and physics",
          },
        ],
      },
      {
        id: "aviation",
        name: "Aviation Units",
        units: [
          {
            id: "knot",
            name: "Knot",
            symbol: "kn",
            baseRatio: 0.514444,
            isBaseUnit: false,
            precision: 3,
            description: "Nautical mile per hour",
            context: "Aviation and marine navigation",
          },
          {
            id: "mach",
            name: "Mach",
            symbol: "M",
            baseRatio: 343,
            isBaseUnit: false,
            precision: 3,
            description: "Speed of sound at sea level",
            context: "High-speed aviation",
          },
        ],
      },
    ],
  },
  {
    id: "time",
    name: "Time",
    icon: "T",
    description: "Time duration measurements",
    groups: [
      {
        id: "common",
        name: "Common Units",
        units: [
          {
            id: "second",
            name: "Second",
            symbol: "s",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI base unit of time",
            context: "Scientific and precise measurements",
          },
          {
            id: "minute",
            name: "Minute",
            symbol: "min",
            baseRatio: 60,
            isBaseUnit: false,
            precision: 3,
            description: "60 seconds",
            context: "Short duration measurements",
          },
          {
            id: "hour",
            name: "Hour",
            symbol: "h",
            baseRatio: 3600,
            isBaseUnit: false,
            precision: 3,
            description: "60 minutes",
            context: "Daily time measurements",
          },
          {
            id: "day",
            name: "Day",
            symbol: "d",
            baseRatio: 86400,
            isBaseUnit: false,
            precision: 6,
            description: "24 hours",
            context: "Daily and weekly planning",
          },
          {
            id: "week",
            name: "Week",
            symbol: "wk",
            baseRatio: 604800,
            isBaseUnit: false,
            precision: 6,
            description: "7 days",
            context: "Weekly planning and scheduling",
          },
          {
            id: "month",
            name: "Month",
            symbol: "mo",
            baseRatio: 2629746,
            isBaseUnit: false,
            precision: 6,
            description: "Average 30.44 days",
            context: "Monthly planning and billing",
          },
          {
            id: "year",
            name: "Year",
            symbol: "yr",
            baseRatio: 31556952,
            isBaseUnit: false,
            precision: 6,
            description: "365.25 days",
            context: "Annual planning and age",
          },
        ],
      },
      {
        id: "precise",
        name: "Precise Units",
        units: [
          {
            id: "millisecond",
            name: "Millisecond",
            symbol: "ms",
            baseRatio: 0.001,
            isBaseUnit: false,
            precision: 3,
            description: "1/1000 of a second",
            context: "Computer and reaction times",
          },
          {
            id: "microsecond",
            name: "Microsecond",
            symbol: "μs",
            baseRatio: 1e-6,
            isBaseUnit: false,
            precision: 2,
            scientificNotation: true,
            description: "1/1,000,000 of a second",
            context: "Electronics and computing",
          },
          {
            id: "nanosecond",
            name: "Nanosecond",
            symbol: "ns",
            baseRatio: 1e-9,
            isBaseUnit: false,
            precision: 2,
            scientificNotation: true,
            description: "1/1,000,000,000 of a second",
            context: "High-speed electronics",
          },
        ],
      },
    ],
  },
  {
    id: "pressure",
    name: "Pressure",
    icon: "P",
    description: "Pressure and stress measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "pascal",
            name: "Pascal",
            symbol: "Pa",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI unit of pressure",
            context: "Scientific and engineering calculations",
          },
          {
            id: "kilopascal",
            name: "Kilopascal",
            symbol: "kPa",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 3,
            description: "1000 pascals",
            context: "Tire pressure and engineering",
          },
          {
            id: "megapascal",
            name: "Megapascal",
            symbol: "MPa",
            baseRatio: 1000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000 pascals",
            context: "Material strength and high pressure",
          },
          {
            id: "bar",
            name: "Bar",
            symbol: "bar",
            baseRatio: 100000,
            isBaseUnit: false,
            precision: 3,
            description: "100,000 pascals",
            context: "Weather and atmospheric pressure",
          },
          {
            id: "atmosphere",
            name: "Atmosphere",
            symbol: "atm",
            baseRatio: 101325,
            isBaseUnit: false,
            precision: 3,
            description: "Standard atmospheric pressure",
            context: "Weather and diving",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "psi",
            name: "Pounds per Square Inch",
            symbol: "psi",
            baseRatio: 6894.76,
            isBaseUnit: false,
            precision: 3,
            description: "Pressure per square inch",
            context: "Tire pressure and industrial use",
          },
          {
            id: "torr",
            name: "Torr",
            symbol: "Torr",
            baseRatio: 133.322,
            isBaseUnit: false,
            precision: 3,
            description: "1/760 of an atmosphere",
            context: "Vacuum and laboratory measurements",
          },
          {
            id: "mmhg",
            name: "Millimeter of Mercury",
            symbol: "mmHg",
            baseRatio: 133.322,
            isBaseUnit: false,
            precision: 3,
            description: "Pressure of 1mm mercury column",
            context: "Blood pressure and medical use",
          },
        ],
      },
    ],
  },
  {
    id: "power",
    name: "Power",
    icon: "P",
    description: "Power and energy rate measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "watt",
            name: "Watt",
            symbol: "W",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI unit of power",
            context: "Electrical power and energy consumption",
          },
          {
            id: "kilowatt",
            name: "Kilowatt",
            symbol: "kW",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 3,
            description: "1000 watts",
            context: "Household and industrial power",
          },
          {
            id: "megawatt",
            name: "Megawatt",
            symbol: "MW",
            baseRatio: 1000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000 watts",
            context: "Power plants and large facilities",
          },
          {
            id: "gigawatt",
            name: "Gigawatt",
            symbol: "GW",
            baseRatio: 1000000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000,000 watts",
            context: "National power grid and large plants",
          },
        ],
      },
      {
        id: "imperial",
        name: "Imperial Units",
        units: [
          {
            id: "horsepower",
            name: "Horsepower",
            symbol: "hp",
            baseRatio: 745.7,
            isBaseUnit: false,
            precision: 3,
            description: "Mechanical power unit",
            context: "Engine and motor power ratings",
          },
          {
            id: "btu_per_hour",
            name: "BTU per Hour",
            symbol: "BTU/h",
            baseRatio: 0.293071,
            isBaseUnit: false,
            precision: 3,
            description: "British Thermal Unit per hour",
            context: "Heating and cooling systems",
          },
        ],
      },
    ],
  },
  {
    id: "digital",
    name: "Digital Storage",
    icon: "D",
    description: "Digital data storage measurements",
    groups: [
      {
        id: "bytes",
        name: "Byte Units",
        units: [
          {
            id: "byte",
            name: "Byte",
            symbol: "B",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "Basic unit of digital storage",
            context: "File sizes and memory",
          },
          {
            id: "kilobyte",
            name: "Kilobyte",
            symbol: "KB",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 3,
            description: "1000 bytes",
            context: "Small files and text documents",
          },
          {
            id: "megabyte",
            name: "Megabyte",
            symbol: "MB",
            baseRatio: 1000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000 bytes",
            context: "Photos and medium files",
          },
          {
            id: "gigabyte",
            name: "Gigabyte",
            symbol: "GB",
            baseRatio: 1000000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000,000 bytes",
            context: "Videos and large files",
          },
          {
            id: "terabyte",
            name: "Terabyte",
            symbol: "TB",
            baseRatio: 1000000000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000,000,000 bytes",
            context: "Hard drives and large storage",
          },
        ],
      },
      {
        id: "binary",
        name: "Binary Units",
        units: [
          {
            id: "kibibyte",
            name: "Kibibyte",
            symbol: "KiB",
            baseRatio: 1024,
            isBaseUnit: false,
            precision: 3,
            description: "1024 bytes",
            context: "Computer memory and binary storage",
          },
          {
            id: "mebibyte",
            name: "Mebibyte",
            symbol: "MiB",
            baseRatio: 1048576,
            isBaseUnit: false,
            precision: 6,
            description: "1024 kibibytes",
            context: "RAM and binary file sizes",
          },
          {
            id: "gibibyte",
            name: "Gibibyte",
            symbol: "GiB",
            baseRatio: 1073741824,
            isBaseUnit: false,
            precision: 6,
            description: "1024 mebibytes",
            context: "System memory and storage",
          },
          {
            id: "tebibyte",
            name: "Tebibyte",
            symbol: "TiB",
            baseRatio: 1099511627776,
            isBaseUnit: false,
            precision: 6,
            description: "1024 gibibytes",
            context: "Large storage systems",
          },
        ],
      },
      {
        id: "bits",
        name: "Bit Units",
        units: [
          {
            id: "bit",
            name: "Bit",
            symbol: "bit",
            baseRatio: 0.125,
            isBaseUnit: false,
            precision: 3,
            description: "1/8 of a byte",
            context: "Data transmission and networking",
          },
          {
            id: "kilobit",
            name: "Kilobit",
            symbol: "kbit",
            baseRatio: 125,
            isBaseUnit: false,
            precision: 3,
            description: "1000 bits",
            context: "Network and internet speeds",
          },
          {
            id: "megabit",
            name: "Megabit",
            symbol: "Mbit",
            baseRatio: 125000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000 bits",
            context: "Broadband internet speeds",
          },
          {
            id: "gigabit",
            name: "Gigabit",
            symbol: "Gbit",
            baseRatio: 125000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000,000 bits",
            context: "High-speed network connections",
          },
        ],
      },
    ],
  },
  {
    id: "angle",
    name: "Angle",
    icon: "A",
    description: "Angular measurements",
    groups: [
      {
        id: "common",
        name: "Common Units",
        units: [
          {
            id: "degree",
            name: "Degree",
            symbol: "°",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "1/360 of a full rotation",
            context: "Navigation and geometry",
          },
          {
            id: "radian",
            name: "Radian",
            symbol: "rad",
            baseRatio: 57.2958,
            isBaseUnit: false,
            precision: 6,
            description: "SI unit of angle",
            context: "Mathematics and physics",
          },
          {
            id: "gradian",
            name: "Gradian",
            symbol: "grad",
            baseRatio: 0.9,
            isBaseUnit: false,
            precision: 6,
            description: "1/400 of a full rotation",
            context: "Surveying and mapping",
          },
          {
            id: "turn",
            name: "Turn",
            symbol: "turn",
            baseRatio: 360,
            isBaseUnit: false,
            precision: 6,
            description: "Full rotation",
            context: "Rotational mechanics",
          },
        ],
      },
      {
        id: "navigation",
        name: "Navigation Units",
        units: [
          {
            id: "mil",
            name: "Mil",
            symbol: "mil",
            baseRatio: 0.05625,
            isBaseUnit: false,
            precision: 6,
            description: "1/6400 of a full rotation",
            context: "Military navigation",
          },
          {
            id: "arcminute",
            name: "Arcminute",
            symbol: "'",
            baseRatio: 0.0166667,
            isBaseUnit: false,
            precision: 6,
            description: "1/60 of a degree",
            context: "Astronomy and navigation",
          },
          {
            id: "arcsecond",
            name: "Arcsecond",
            symbol: '"',
            baseRatio: 0.000277778,
            isBaseUnit: false,
            precision: 6,
            description: "1/3600 of a degree",
            context: "Precise angular measurements",
          },
        ],
      },
    ],
  },
  {
    id: "frequency",
    name: "Frequency",
    icon: "F",
    description: "Frequency and oscillation measurements",
    groups: [
      {
        id: "common",
        name: "Common Units",
        units: [
          {
            id: "hertz",
            name: "Hertz",
            symbol: "Hz",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI unit of frequency",
            context: "Sound and electrical frequencies",
          },
          {
            id: "kilohertz",
            name: "Kilohertz",
            symbol: "kHz",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 3,
            description: "1000 hertz",
            context: "Audio frequencies",
          },
          {
            id: "megahertz",
            name: "Megahertz",
            symbol: "MHz",
            baseRatio: 1000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000 hertz",
            context: "Radio and computer frequencies",
          },
          {
            id: "gigahertz",
            name: "Gigahertz",
            symbol: "GHz",
            baseRatio: 1000000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000,000 hertz",
            context: "Microwave and processor frequencies",
          },
        ],
      },
      {
        id: "rotational",
        name: "Rotational Units",
        units: [
          {
            id: "rpm",
            name: "Revolutions per Minute",
            symbol: "rpm",
            baseRatio: 0.0166667,
            isBaseUnit: false,
            precision: 3,
            description: "Rotations per minute",
            context: "Motors and mechanical systems",
          },
          {
            id: "rps",
            name: "Revolutions per Second",
            symbol: "rps",
            baseRatio: 1,
            isBaseUnit: false,
            precision: 3,
            description: "Rotations per second",
            context: "High-speed rotating equipment",
          },
        ],
      },
    ],
  },
  // 新增能量分类 - 演示简单和复杂转换关系
  {
    id: "energy",
    name: "Energy",
    icon: "E",
    description: "Energy and work measurements",
    groups: [
      {
        id: "metric",
        name: "Metric Units",
        units: [
          {
            id: "joule",
            name: "Joule",
            symbol: "J",
            baseRatio: 1,
            isBaseUnit: true,
            precision: 6,
            description: "SI unit of energy",
            context: "Physics and engineering calculations",
          },
          {
            id: "kilojoule",
            name: "Kilojoule",
            symbol: "kJ",
            baseRatio: 1000,
            isBaseUnit: false,
            precision: 3,
            description: "1000 joules",
            context: "Food energy and larger energy measurements",
          },
          {
            id: "megajoule",
            name: "Megajoule",
            symbol: "MJ",
            baseRatio: 1000000,
            isBaseUnit: false,
            precision: 6,
            description: "1,000,000 joules",
            context: "Industrial energy and fuel content",
          },
          {
            id: "calorie",
            name: "Calorie",
            symbol: "cal",
            baseRatio: 4.184, // 1 cal = 4.184 J (简单线性转换)
            isBaseUnit: false,
            precision: 3,
            description: "Energy to heat 1g water by 1°C",
            context: "Food energy and nutrition",
          },
          {
            id: "kilocalorie",
            name: "Kilocalorie",
            symbol: "kcal",
            baseRatio: 4184, // 1 kcal = 4184 J
            isBaseUnit: false,
            precision: 3,
            description: "1000 calories, food Calorie",
            context: "Food energy and nutrition labels",
          },
        ],
      },
      {
        id: "electrical",
        name: "Electrical Units",
        units: [
          {
            id: "watt_hour",
            name: "Watt Hour",
            symbol: "Wh",
            baseRatio: 3600, // 1 Wh = 3600 J
            isBaseUnit: false,
            precision: 3,
            description: "Energy consumed by 1W in 1 hour",
            context: "Electrical energy consumption",
          },
          {
            id: "kilowatt_hour",
            name: "Kilowatt Hour",
            symbol: "kWh",
            baseRatio: 3600000, // 1 kWh = 3,600,000 J
            isBaseUnit: false,
            precision: 3,
            description: "1000 watt hours",
            context: "Household electricity billing",
          },
          {
            id: "electron_volt",
            name: "Electron Volt",
            symbol: "eV",
            baseRatio: 1.602176634e-19, // 极小的能量单位
            isBaseUnit: false,
            precision: 2,
            scientificNotation: true,
            description: "Energy gained by electron through 1V potential",
            context: "Atomic and particle physics",
          },
        ],
      },
      {
        id: "thermal",
        name: "Thermal Units",
        units: [
          {
            id: "btu",
            name: "British Thermal Unit",
            symbol: "BTU",
            baseRatio: 1055.06, // 1 BTU = 1055.06 J
            isBaseUnit: false,
            precision: 3,
            description: "Energy to heat 1 pound water by 1°F",
            context: "Heating and cooling systems",
          },
          {
            id: "therm",
            name: "Therm",
            symbol: "thm",
            baseRatio: 105506000, // 1 thm = 100,000 BTU
            isBaseUnit: false,
            precision: 6,
            description: "100,000 BTU",
            context: "Natural gas billing and heating",
          },
        ],
      },
      {
        id: "nuclear",
        name: "Nuclear Units",
        units: [
          {
            id: "tnt_equivalent",
            name: "TNT Equivalent",
            symbol: "TNT",
            baseRatio: 4184000000, // 1 kg TNT = ~4.184 GJ
            isBaseUnit: false,
            precision: 6,
            scientificNotation: true,
            description: "Energy equivalent to 1kg of TNT",
            context: "Explosive energy and nuclear weapons",
          },
        ],
      },
    ],
  },
];
